security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity: { class: App/Entity/User, property: email }
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            pattern: ^/
            form_login:
                provider: app_user_provider
                enable_csrf: true
                login_path: security_login
                check_path: security_login
                default_target_path: homepage
                always_use_default_target_path: false
                use_referer: true
            logout:
                path: security_logout
            custom_authenticators:
                - App\Security\AppLoginFormAuthentification
    access_control:
        - { path: ^/login, role: PUBLIC_ACCESS }
        - { path: ^/, role: ROLE_USER }
