security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity: { class: App/Entity/User, property: email }
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                check_path: security_login
                login_path: security_login
                enable_csrf: true
                default_target_path: homepage
            logout:
                path: security_logout
                target: homepage
                csrf_parameter: logout
                csrf_token_generator: security.csrf.token_manager
            entry_point: 'form_login'

            #custom_authenticators:
            #    - App\Security\AppLoginFormAuthentification
            #logout:
            #    path: security_logout
            #    target: homepage
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
